# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
dist: bionic

python:
  - '3.7'

services:
  - docker

cache:
  pip: true

env:
  global:
  - PGDATABASE=postgres
  - PGHOST=localhost
  - PGUSER=postgres
  - PGPASS=''
  - PGPORT=5432
  - POSTGRES_IMAGE=mdillon/postgis:11
  - DATABASE_URL=postgres://${PGUSER}:${PGPASS}@${PGHOST}:${PGPORT}/${PGDATABASE}

before_install:
  - sudo service postgresql stop
  - docker run --rm --name pg-docker -d -p ${PGPORT}:5432 --tmpfs /var/lib/postgresql/data:rw ${POSTGRES_IMAGE}
  - docker ps

install:
  - pip install -r requirements/development.txt

script:
- flake8
- pytest --cov -v --tb=native
- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: openhouce-dev
    qa: openhouce-qa
    prod: openhouce-prod
  on:
    repo: ShubhamBansal1997/openhouce-web

